server:
  port: 15000
spring:
  application:
    name: java-demo
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 3
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 3
  httpclient:
    enabled: true
  okhttp:
    enabled: true
  ReadTimeout: 90000
  ConnectTimeout: 90000

hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true